# Generated by Django 5.2.5 on 2025-08-14 19:34

import django.db.models.deletion
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='listings.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('euro_standard', models.CharField(blank=True, max_length=10)),
                ('video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.bodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city')),
                ('drive_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.drivetype')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.fueltype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.carmodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.transmissiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.listing_image_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['brand', 'name'], name='listings_ca_brand_i_5962c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name')},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'is_active'], name='listings_li_status_7f433c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['brand', 'model'], name='listings_li_brand_i_d88723_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_li_city_id_682538_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['year'], name='listings_li_year_590972_idx'),
        ),
    ]
